/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SuperRouteImport } from './routes/super'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as QsaInfoRouteImport } from './routes/qsa.info'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as SuperIndexRouteImport } from './routes/super.index'
import { Route as SuperAboutRouteImport } from './routes/super.about'
import { Route as SuperBlogRouteImport } from './routes/super.blog'
import { Route as SuperContactsRouteImport } from './routes/super.contacts'
import { Route as SuperDashboardRouteImport } from './routes/super.dashboard'
import { Route as SuperGalleryRouteImport } from './routes/super.gallery'
import { Route as SuperHeroRouteImport } from './routes/super.hero'
import { Route as SuperInquiriesRouteImport } from './routes/super.inquiries'
import { Route as SuperLoginRouteImport } from './routes/super.login'
import { Route as SuperServicesRouteImport } from './routes/super.services'
import { Route as SuperSettingsRouteImport } from './routes/super.settings'
import { Route as SuperSocialsRouteImport } from './routes/super.socials'
import { Route as SuperTeamRouteImport } from './routes/super.team'
import { Route as SuperUsersRouteImport } from './routes/super.users'
import { Route as ApiPublicMediaIdRouteImport } from './routes/api/public/media.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperRoute = SuperRouteImport.update({
  id: '/super',
  path: '/super',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const QsaInfoRoute = QsaInfoRouteImport.update({
  id: '/qsa/info',
  path: '/qsa/info',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperIndexRoute = SuperIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuperRoute,
} as any)
const SuperAboutRoute = SuperAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SuperRoute,
} as any)
const SuperBlogRoute = SuperBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => SuperRoute,
} as any)
const SuperContactsRoute = SuperContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => SuperRoute,
} as any)
const SuperDashboardRoute = SuperDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => SuperRoute,
} as any)
const SuperGalleryRoute = SuperGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => SuperRoute,
} as any)
const SuperHeroRoute = SuperHeroRouteImport.update({
  id: '/hero',
  path: '/hero',
  getParentRoute: () => SuperRoute,
} as any)
const SuperInquiriesRoute = SuperInquiriesRouteImport.update({
  id: '/inquiries',
  path: '/inquiries',
  getParentRoute: () => SuperRoute,
} as any)
const SuperLoginRoute = SuperLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => SuperRoute,
} as any)
const SuperServicesRoute = SuperServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => SuperRoute,
} as any)
const SuperSettingsRoute = SuperSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => SuperRoute,
} as any)
const SuperSocialsRoute = SuperSocialsRouteImport.update({
  id: '/socials',
  path: '/socials',
  getParentRoute: () => SuperRoute,
} as any)
const SuperTeamRoute = SuperTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => SuperRoute,
} as any)
const SuperUsersRoute = SuperUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => SuperRoute,
} as any)
const ApiPublicMediaIdRoute = ApiPublicMediaIdRouteImport.update({
  id: '/api/public/media/$id',
  path: '/api/public/media/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/contacts': typeof ContactsRoute
  '/gallery': typeof GalleryRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/super': typeof SuperRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/qsa/info': typeof QsaInfoRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/super/about': typeof SuperAboutRoute
  '/super/blog': typeof SuperBlogRoute
  '/super/contacts': typeof SuperContactsRoute
  '/super/dashboard': typeof SuperDashboardRoute
  '/super/gallery': typeof SuperGalleryRoute
  '/super/hero': typeof SuperHeroRoute
  '/super/inquiries': typeof SuperInquiriesRoute
  '/super/login': typeof SuperLoginRoute
  '/super/services': typeof SuperServicesRoute
  '/super/settings': typeof SuperSettingsRoute
  '/super/socials': typeof SuperSocialsRoute
  '/super/team': typeof SuperTeamRoute
  '/super/users': typeof SuperUsersRoute
  '/blog/': typeof BlogIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/super/': typeof SuperIndexRoute
  '/api/public/media/$id': typeof ApiPublicMediaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/contacts': typeof ContactsRoute
  '/gallery': typeof GalleryRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/qsa/info': typeof QsaInfoRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/super/about': typeof SuperAboutRoute
  '/super/blog': typeof SuperBlogRoute
  '/super/contacts': typeof SuperContactsRoute
  '/super/dashboard': typeof SuperDashboardRoute
  '/super/gallery': typeof SuperGalleryRoute
  '/super/hero': typeof SuperHeroRoute
  '/super/inquiries': typeof SuperInquiriesRoute
  '/super/login': typeof SuperLoginRoute
  '/super/services': typeof SuperServicesRoute
  '/super/settings': typeof SuperSettingsRoute
  '/super/socials': typeof SuperSocialsRoute
  '/super/team': typeof SuperTeamRoute
  '/super/users': typeof SuperUsersRoute
  '/blog': typeof BlogIndexRoute
  '/services': typeof ServicesIndexRoute
  '/super': typeof SuperIndexRoute
  '/api/public/media/$id': typeof ApiPublicMediaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/contacts': typeof ContactsRoute
  '/gallery': typeof GalleryRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/super': typeof SuperRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/qsa/info': typeof QsaInfoRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/super/about': typeof SuperAboutRoute
  '/super/blog': typeof SuperBlogRoute
  '/super/contacts': typeof SuperContactsRoute
  '/super/dashboard': typeof SuperDashboardRoute
  '/super/gallery': typeof SuperGalleryRoute
  '/super/hero': typeof SuperHeroRoute
  '/super/inquiries': typeof SuperInquiriesRoute
  '/super/login': typeof SuperLoginRoute
  '/super/services': typeof SuperServicesRoute
  '/super/settings': typeof SuperSettingsRoute
  '/super/socials': typeof SuperSocialsRoute
  '/super/team': typeof SuperTeamRoute
  '/super/users': typeof SuperUsersRoute
  '/blog/': typeof BlogIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/super/': typeof SuperIndexRoute
  '/api/public/media/$id': typeof ApiPublicMediaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-us'
    | '/contacts'
    | '/gallery'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/super'
    | '/blog/$slug'
    | '/qsa/info'
    | '/services/$slug'
    | '/super/about'
    | '/super/blog'
    | '/super/contacts'
    | '/super/dashboard'
    | '/super/gallery'
    | '/super/hero'
    | '/super/inquiries'
    | '/super/login'
    | '/super/services'
    | '/super/settings'
    | '/super/socials'
    | '/super/team'
    | '/super/users'
    | '/blog/'
    | '/services/'
    | '/super/'
    | '/api/public/media/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/contacts'
    | '/gallery'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/qsa/info'
    | '/services/$slug'
    | '/super/about'
    | '/super/blog'
    | '/super/contacts'
    | '/super/dashboard'
    | '/super/gallery'
    | '/super/hero'
    | '/super/inquiries'
    | '/super/login'
    | '/super/services'
    | '/super/settings'
    | '/super/socials'
    | '/super/team'
    | '/super/users'
    | '/blog'
    | '/services'
    | '/super'
    | '/api/public/media/$id'
  id:
    | '__root__'
    | '/'
    | '/about-us'
    | '/contacts'
    | '/gallery'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/super'
    | '/blog/$slug'
    | '/qsa/info'
    | '/services/$slug'
    | '/super/about'
    | '/super/blog'
    | '/super/contacts'
    | '/super/dashboard'
    | '/super/gallery'
    | '/super/hero'
    | '/super/inquiries'
    | '/super/login'
    | '/super/services'
    | '/super/settings'
    | '/super/socials'
    | '/super/team'
    | '/super/users'
    | '/blog/'
    | '/services/'
    | '/super/'
    | '/api/public/media/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutUsRoute: typeof AboutUsRoute
  ContactsRoute: typeof ContactsRoute
  GalleryRoute: typeof GalleryRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SuperRoute: typeof SuperRouteWithChildren
  BlogSlugRoute: typeof BlogSlugRoute
  QsaInfoRoute: typeof QsaInfoRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  ApiPublicMediaIdRoute: typeof ApiPublicMediaIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super': {
      id: '/super'
      path: '/super'
      fullPath: '/super'
      preLoaderRoute: typeof SuperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qsa/info': {
      id: '/qsa/info'
      path: '/qsa/info'
      fullPath: '/qsa/info'
      preLoaderRoute: typeof QsaInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super/': {
      id: '/super/'
      path: '/'
      fullPath: '/super/'
      preLoaderRoute: typeof SuperIndexRouteImport
      parentRoute: typeof SuperRoute
    }
    '/super/about': {
      id: '/super/about'
      path: '/about'
      fullPath: '/super/about'
      preLoaderRoute: typeof SuperAboutRouteImport
      parentRoute: typeof SuperRoute
    }
    '/super/blog': {
      id: '/super/blog'
      path: '/blog'
      fullPath: '/super/blog'
      preLoaderRoute: typeof SuperBlogRouteImport
      parentRoute: typeof SuperRoute
    }
    '/super/contacts': {
      id: '/super/contacts'
      path: '/contacts'
      fullPath: '/super/contacts'
      preLoaderRoute: typeof SuperContactsRouteImport
      parentRoute: typeof SuperRoute
    }
    '/super/dashboard': {
      id: '/super/dashboard'
      path: '/dashboard'
      fullPath: '/super/dashboard'
      preLoaderRoute: typeof SuperDashboardRouteImport
      parentRoute: typeof SuperRoute
    }
    '/super/gallery': {
      id: '/super/gallery'
      path: '/gallery'
      fullPath: '/super/gallery'
      preLoaderRoute: typeof SuperGalleryRouteImport
      parentRoute: typeof SuperRoute
    }
    '/super/hero': {
      id: '/super/hero'
      path: '/hero'
      fullPath: '/super/hero'
      preLoaderRoute: typeof SuperHeroRouteImport
      parentRoute: typeof SuperRoute
    }
    '/super/inquiries': {
      id: '/super/inquiries'
      path: '/inquiries'
      fullPath: '/super/inquiries'
      preLoaderRoute: typeof SuperInquiriesRouteImport
      parentRoute: typeof SuperRoute
    }
    '/super/login': {
      id: '/super/login'
      path: '/login'
      fullPath: '/super/login'
      preLoaderRoute: typeof SuperLoginRouteImport
      parentRoute: typeof SuperRoute
    }
    '/super/services': {
      id: '/super/services'
      path: '/services'
      fullPath: '/super/services'
      preLoaderRoute: typeof SuperServicesRouteImport
      parentRoute: typeof SuperRoute
    }
    '/super/settings': {
      id: '/super/settings'
      path: '/settings'
      fullPath: '/super/settings'
      preLoaderRoute: typeof SuperSettingsRouteImport
      parentRoute: typeof SuperRoute
    }
    '/super/socials': {
      id: '/super/socials'
      path: '/socials'
      fullPath: '/super/socials'
      preLoaderRoute: typeof SuperSocialsRouteImport
      parentRoute: typeof SuperRoute
    }
    '/super/team': {
      id: '/super/team'
      path: '/team'
      fullPath: '/super/team'
      preLoaderRoute: typeof SuperTeamRouteImport
      parentRoute: typeof SuperRoute
    }
    '/super/users': {
      id: '/super/users'
      path: '/users'
      fullPath: '/super/users'
      preLoaderRoute: typeof SuperUsersRouteImport
      parentRoute: typeof SuperRoute
    }
    '/api/public/media/$id': {
      id: '/api/public/media/$id'
      path: '/api/public/media/$id'
      fullPath: '/api/public/media/$id'
      preLoaderRoute: typeof ApiPublicMediaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SuperRouteChildren {
  SuperAboutRoute: typeof SuperAboutRoute
  SuperBlogRoute: typeof SuperBlogRoute
  SuperContactsRoute: typeof SuperContactsRoute
  SuperDashboardRoute: typeof SuperDashboardRoute
  SuperGalleryRoute: typeof SuperGalleryRoute
  SuperHeroRoute: typeof SuperHeroRoute
  SuperInquiriesRoute: typeof SuperInquiriesRoute
  SuperLoginRoute: typeof SuperLoginRoute
  SuperServicesRoute: typeof SuperServicesRoute
  SuperSettingsRoute: typeof SuperSettingsRoute
  SuperSocialsRoute: typeof SuperSocialsRoute
  SuperTeamRoute: typeof SuperTeamRoute
  SuperUsersRoute: typeof SuperUsersRoute
  SuperIndexRoute: typeof SuperIndexRoute
}

const SuperRouteChildren: SuperRouteChildren = {
  SuperAboutRoute: SuperAboutRoute,
  SuperBlogRoute: SuperBlogRoute,
  SuperContactsRoute: SuperContactsRoute,
  SuperDashboardRoute: SuperDashboardRoute,
  SuperGalleryRoute: SuperGalleryRoute,
  SuperHeroRoute: SuperHeroRoute,
  SuperInquiriesRoute: SuperInquiriesRoute,
  SuperLoginRoute: SuperLoginRoute,
  SuperServicesRoute: SuperServicesRoute,
  SuperSettingsRoute: SuperSettingsRoute,
  SuperSocialsRoute: SuperSocialsRoute,
  SuperTeamRoute: SuperTeamRoute,
  SuperUsersRoute: SuperUsersRoute,
  SuperIndexRoute: SuperIndexRoute,
}

const SuperRouteWithChildren = SuperRoute._addFileChildren(SuperRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutUsRoute: AboutUsRoute,
  ContactsRoute: ContactsRoute,
  GalleryRoute: GalleryRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SuperRoute: SuperRouteWithChildren,
  BlogSlugRoute: BlogSlugRoute,
  QsaInfoRoute: QsaInfoRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  ApiPublicMediaIdRoute: ApiPublicMediaIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
